# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, to='scheduler.Chore'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), '5 minutes'), (datetime.timedelta(0, 900), '10 minutes'), (datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes')]),
        ),
    ]
