# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 05:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20170706_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None),
        ),
    ]
