# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:17
from __future__ import unicode_literals

import chorez.scheduler.models
from django.db import migrations, models

from django import forms
from django.contrib.postgres.fields import ArrayField
from django.db import models


class ChoiceArrayField(ArrayField):
    """
    Thanks https://gist.github.com/danni/f55c4ce19598b2b345ef

    A field that allows us to store an array of choices.

    Uses Django 1.9's postgres ArrayField
    and a MultipleChoiceField for its formfield.

    Usage:
    choices = ChoiceArrayField(models.CharField(max_length=...,
                                                choices=(...,)),
                               default=[...])
    """

    def formfield(self, **kwargs):
        defaults = {
            'form_class': forms.MultipleChoiceField,
            'choices': self.base_field.choices,
        }
        defaults.update(kwargs)
        # Skip our parent's formfield implementation completely as we don't
        # care for it.
        # pylint:disable=bad-super-call
        return super(ArrayField, self).formfield(**defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_chore_last_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='days',
            field=ChoiceArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), blank=True, default=chorez.scheduler.models.default_days, size=None),
        ),
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='This chore must be done once every N days'),
        ),
    ]
