# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:42
from __future__ import unicode_literals

import chorez.scheduler.models
import datetime
from django.db import migrations, models


def migrate_freq(apps, schema_editor):
    Chore = apps.get_model('scheduler', 'Chore')
    for chore in Chore.objects.all():
        chore.frequency2 = datetime.timedelta(days=chore.frequency)
        chore.save()


def unmigrate_freq(apps, schema_editor):
    Chore = apps.get_model('scheduler', 'Chore')
    for chore in Chore.objects.all():
        chore.frequency = chore.frequency2.days
        chore.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20170709_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='frequency2',
            field=models.DurationField(choices=[(datetime.timedelta(1), 'Daily'), (datetime.timedelta(7), 'Weekly'), (datetime.timedelta(14), 'Bi-weekly'), (datetime.timedelta(30), 'Monthly')], default=datetime.timedelta(days=1)),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_freq, unmigrate_freq),
        migrations.RemoveField(
            model_name='chore',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='chore',
            name='last_done',
            field=models.DateField(blank=True, default=chorez.scheduler.models.default_last_done),
        ),
    ]
