# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20170709_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='frequency2',
            new_name='frequency',
        ),
    ]
