# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20170709_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='days',
        ),
        migrations.AddField(
            model_name='chore',
            name='weekends_only',
            field=models.BooleanField(default=False),
        ),
    ]
