# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20170709_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='weekday_availability',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 3600), '60 minutes')], default=datetime.timedelta(0, 900)),
        ),
        migrations.AddField(
            model_name='person',
            name='weekend_availability',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 3600), '60 minutes')], default=datetime.timedelta(0, 900)),
        ),
        migrations.AlterField(
            model_name='chore',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), '5 minutes'), (datetime.timedelta(0, 600), '10 minutes'), (datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes')]),
        ),
    ]
