# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20170709_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='chore',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
        migrations.AddField(
            model_name='chore',
            name='snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='frequency',
            field=models.DurationField(choices=[(datetime.timedelta(1), 'Daily'), (datetime.timedelta(2), 'Every other day'), (datetime.timedelta(3, 43200), 'Twice a week'), (datetime.timedelta(7), 'Weekly'), (datetime.timedelta(14), 'Every other week'), (datetime.timedelta(30), 'Monthly')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='weekday_availability',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 2700), '45 minutes'), (datetime.timedelta(0, 3600), '60 minutes')], default=datetime.timedelta(0, 900)),
        ),
        migrations.AlterField(
            model_name='person',
            name='weekend_availability',
            field=models.DurationField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 2700), '45 minutes'), (datetime.timedelta(0, 3600), '60 minutes')], default=datetime.timedelta(0, 900)),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
